### ISSUE TITLE
ECCO v4r4 on Sciserver 

### ISSUE THREAD

**Issue by asiddi24** [malmans2/oceanspy#199]
* OceanSpy version: 0.2.0

### Description

Just a heads up that since the test data that @Mikejmnez had put up in Sciserver works great with Oceanspy, I'll now be uploading the entire ECCOv4r4 dataset (i.e with variables required to close heat/salt/volume budgets) to it. 

### What I Did

- [x] Finished converting the entire dataset into zarr format.
- [x] Need to test intake catalog entry on my fork. Once this works, and we can close and merge #168 as well.
- [x] Update Oceanography image on Sciserver.

**Comment by ThomasHaine** [comment]
Great news @asiddi24 !

**Comment by Mikejmnez** [comment]
awesome!

**Comment by Mikejmnez** [comment]
closing via PR #222
