### ISSUE TITLE
Updating Oceanography image in SciServer

### ISSUE THREAD

**Issue by asiddi24** [malmans2/oceanspy#220]
* OceanSpy version:0.2.0

Going to try and send Mitya the new environment file to update the oceanography image. @malmans2 @Mikejmnez any advice on running compatibility tests for the packages in the updated file ? Referencing https://github.com/hainegroup/oceanspy/pull/218#issuecomment-1040094347 here.

**Comment by Mikejmnez** [comment]
One thing I am trying to do right now, is to extract the environment that I am using on Sciserver as a .txt file (there I have several pip installs that I know run well with oceanspy and the new stuff). 

Then, I am trying to use that .txt file to create a test environment in my local machine where I can run ```oceanspy``` and its tests.

**Comment by asiddi24** [comment]
Got it. I'm going to update the current packages in the image and then run the tests on my local and see what happens.

**Comment by malmans2** [comment]
Hi Ali,
I'd try to run the usual tests (see point 8 [here](https://oceanspy.readthedocs.io/en/latest/contributing.html#contributing-to-the-code)), and execute all demo notebooks on SciServer (see notebooks [here](https://github.com/hainegroup/oceanspy/tree/master/docs)).
Make sure python is 3.7,8, or 9 - I think some of our dependencies don't support 3.10 yet.

If you didn't know it already, you can also export to yml:
```
conda env export > environment.yml
```

**Comment by asiddi24** [comment]
> I'd try to run the usual tests (see point 8 [here](https://oceanspy.readthedocs.io/en/latest/contributing.html#contributing-to-the-code)),

Yup, exactly what I'm running right now. I'll also run the demo notebooks. Thanks !
