### ISSUE TITLE
0.5 <= xesfm <= 0.6.2 yields Attribute Error with Regridder

### ISSUE THREAD

**Issue by Mikejmnez** [malmans2/oceanspy#221]
When testing the `Kogur` notebook, and running a (proposed) new environment within `Sciserver`, I got the following error

```python
AttributeError: 'Regridder' object has no attribute 'clean_weight_file'
```

The test environment I was using installed the latest version of `xesmf`, version 0.6.2. @asiddi24 and I noticed that in the current environment.yaml file, we are installing `xesfm !=0.5.0 !=0.5.1`. 

I checked the repository of `xesmf ` and it looks like it has migrated into the general pangeo repository, and while doing so they made substantial changes to the code. They still define the `Regridder` class in their ```frontend.py``` module, but indeed ```clean_weight_file()``` is no longer part of the class since the migration. 

I did find this
https://github.com/JiaweiZhuang/xESMF/issues/11

I think this is another area where we will probably need to change `oceanspy`. For now, I think setting 

```python
xesmf < 0.5
```

will allow us to update the Oceanography image, while we work around these changes.

**Comment by asiddi24** [comment]
I agree, we can just use `xesmf < 0.5.0` for now.

**Comment by malmans2** [comment]
There's a good chance that's the only breaking change affecting us. `xesmf` changed quite a bit, but it also improved. How about we try the opposite?
We remove the `clean_weight_file` lines and we pin `xesmf>=` first version using in-memory weights?

**Comment by malmans2** [comment]
Actually, I thought I took care of it already...
https://github.com/hainegroup/oceanspy/blob/68b0f00b154069d72bd989f8aaa30d91bf3b5582/oceanspy/subsample.py#L1120-L1121
Is there a bug in `xesmf` version attribute?

**Comment by Mikejmnez** [comment]
> Actually, I thought I took care of it already...
> 
> https://github.com/hainegroup/oceanspy/blob/68b0f00b154069d72bd989f8aaa30d91bf3b5582/oceanspy/subsample.py#L1120-L1121
> 
> Is there a bug in `xesmf` version attribute?

I think @malmans2 is correct, the `AttributeError` shows an older snippet of code from oceanspy

![Screen Shot 2022-02-16 at 6 48 43 PM](https://user-images.githubusercontent.com/8241481/154377032-2328b9df-e307-4bfa-b56b-0777fbbb264a.png)
