### ISSUE TITLE
another LLC cutout issue

### ISSUE THREAD

**Issue by renskegelderloos** [malmans2/oceanspy#236]
* OceanSpy version: 0.2.0

### Description

I am trying to make a simple cutout from the ECCO dataset. No data survives the cutout, but it should. Adding a varList makes no difference. The SciServer Oceanography environment runs on python 3.8, which might be part of the problem. 

### What I Did
import oceanspy as ospy
od_ECCO = ospy.open_oceandataset.from_catalog('ECCO')
LabSea_cutout = od_ECCO.subsample.cutout(XRange=[-70,-55],YRange=[55,70],transformation="arctic_crown")

Error message: No data within group of facets (same ordering) survives the cutout.

Traceback:
KeyErrorTraceback (most recent call last)
~/miniconda3/envs/Oceanography/lib/python3.8/site-packages/xarray/core/dataset.py in _construct_dataarray(self, name)
   1171         try:
-> 1172             variable = self._variables[name]
   1173         except KeyError:

KeyError: 'nv'

During handling of the above exception, another exception occurred:

KeyErrorTraceback (most recent call last)
<ipython-input-4-b39b594ea5a6> in <module>
----> 1 LabSea_cutout = od_ECCO.subsample.cutout(XRange=[-70,-55],YRange=[55,70],transformation="arctic_crown")

~/miniconda3/envs/Oceanography/lib/python3.8/site-packages/oceanspy/subsample.py in cutout(self, **kwargs)
   1393     @_functools.wraps(cutout)
   1394     def cutout(self, **kwargs):
-> 1395         return cutout(self._od, **kwargs)
   1396 
   1397     @_functools.wraps(mooring_array)

~/miniconda3/envs/Oceanography/lib/python3.8/site-packages/oceanspy/subsample.py in cutout(od, varList, YRange, XRange, add_Hbdr, mask_outside, ZRange, add_Vbdr, timeRange, timeFreq, sampMethod, dropAxes, transformation, centered)
    369             elif transformation == "arctic_centered":
    370                 _transformation = _llc_trans.arctic_centered
--> 371             dsnew = _transformation(**arg)
    372             dsnew = dsnew.set_coords(co_list)
    373             grid_coords = od.grid_coords

~/miniconda3/envs/Oceanography/lib/python3.8/site-packages/oceanspy/llc_rearrange.py in arctic_crown(self, ds, varlist, centered, faces, drop)
    233         metrics = ["dxC", "dyC", "dxG", "dyG"]
    234 
--> 235         NR_dsnew = init_vars(ds, NR_dsnew, varlist)
    236         R_dsnew = init_vars(ds, R_dsnew, varlist)
    237 

~/miniconda3/envs/Oceanography/lib/python3.8/site-packages/oceanspy/llc_rearrange.py in init_vars(ds, DSNEW, varlist)
    350             ncoords = {dims.X: DSNEW.coords[dims.X]}
    351         elif len(dims) == 2:
--> 352             ncoords = {dims.X: DSNEW.coords[dims.X], dims.Y: DSNEW.coords[dims.Y]}
    353         elif len(dims) == 3:
    354             ncoords = {

~/miniconda3/envs/Oceanography/lib/python3.8/site-packages/xarray/core/coordinates.py in __getitem__(self, key)
    212         if key in self._data.data_vars:
    213             raise KeyError(key)
--> 214         return cast("DataArray", self._data[key])
    215 
    216     def to_dataset(self) -> "Dataset":

~/miniconda3/envs/Oceanography/lib/python3.8/site-packages/xarray/core/dataset.py in __getitem__(self, key)
   1270 
   1271         if hashable(key):
-> 1272             return self._construct_dataarray(key)
   1273         else:
   1274             return self._copy_listed(np.asarray(key))

~/miniconda3/envs/Oceanography/lib/python3.8/site-packages/xarray/core/dataset.py in _construct_dataarray(self, name)
   1172             variable = self._variables[name]
   1173         except KeyError:
-> 1174             _, name, variable = _get_virtual_variable(
   1175                 self._variables, name, self._level_coords, self.dims
   1176             )

~/miniconda3/envs/Oceanography/lib/python3.8/site-packages/xarray/core/dataset.py in _get_virtual_variable(variables, key, level_vars, dim_sizes)
    169         ref_var = dim_var.to_index_variable().get_level_variable(ref_name)
    170     else:
--> 171         ref_var = variables[ref_name]
    172 
    173     if var_name is None:

KeyError: 'nv'

**Comment by Mikejmnez** [comment]
I am a bit confused... I just ran this on Sciserver (Oceanography 2.3)

![Screen Shot 2022-06-28 at 5 12 44 PM](https://user-images.githubusercontent.com/8241481/176289042-6465550e-a043-4d10-a884-8924c027bbd8.png)


I am about to leave the office, but I will check it later or tomorrow morning...

**Comment by renskegelderloos** [comment]
Does your Oceanography 2.3 image have an Oceanography 2.3 environment? The new container that I created today doesn't have that option - only Oceanography. What python version runs your notebook on?

**Comment by Mikejmnez** [comment]
The environment has python 3.9.10. I just created a container with Oceanography 2.3 (that is new image +  right environment). It come with python 3.9.10. And I was able to the code above.

**Comment by renskegelderloos** [comment]
I am so confused, as that is not what I'm getting with a brand new container. But this is clearly a SciServer issue and not an OceanSpy one, so I'll go ahead and close this issue.
