### ISSUE TITLE
pin xesmf < 8.4

### ISSUE THREAD

**Issue by Mikejmnez** [malmans2/oceanspy#291]
### Description

Just a couple of hours ago, as @malmans2 and I were hoping to get a new oceanspy release, there was a new release of ESMpy, which affected how to import `xESMF`. The new version (8.4) leads to the following error in `oceanspy.subsample` which I reproduce by simply just trying to import xesfm on the command line:

<img width="500" alt="fail" src="https://user-images.githubusercontent.com/8241481/207183734-4d3b30e9-f804-4a99-96d8-847a0f9c8308.png">

The issue and temporal solution can be seen here on (xESMF GH repo):

https://github.com/pangeo-data/xESMF/issues/212

Pinning down `esmf < 8.4` (hence installing version `8.3.+`) allows all tests to pass. This is a temporal solution to a problem outside of oceanspy.

Espect a PR soon enough...

**Comment by malmans2** [comment]
I think you can unpin now: https://github.com/pangeo-data/xESMF/issues/217

**Comment by Mikejmnez** [comment]
will do so. I was also making some other little changes. PR coming soon!

**Comment by Mikejmnez** [comment]
closed by #300
