### ISSUE TITLE
The source distribution tarball is an empty package.

### ISSUE THREAD

**Issue by ocefpaf** [malmans2/oceanspy#294]
I'll try to send a PR to fix that ASAP. One can test that by trying to install the latest version from PyPI with pip. See https://github.com/conda-forge/oceanspy-feedstock/pull/9

**Comment by Mikejmnez** [comment]
Thank you @ocefpaf, I was just starting to look into that PR. I'll be waiting for the upcoming PR

**Comment by ocefpaf** [comment]
Almost ready BTW, looking at the sizes of the sdist and the wheel one can see that the sdist has everything in the repo and the wheel is too small to contain the package. BTW, the sdist is quite big! In a time of Python on the web maybe we could reduce the size by excluding some extras that are not part of the package. (I'll add that to my PR.)

![Screenshot from 2022-12-13 15-14-14](https://user-images.githubusercontent.com/950575/207412765-31efcecc-8d02-4ab8-9915-8c9aa77e45fb.png)

**Comment by Mikejmnez** [comment]
thank you again @ocefpaf !
