### ISSUE TITLE
set `add_labels=True` in order to show tick labels on `od.plot.horizontal_section()`

### ISSUE THREAD

**Issue by Mikejmnez** [malmans2/oceanspy#312]
* OceanSpy version:

0.2 and 0.3.2

### Description
Simply when executing, for example as in the current use cases in the documentation (see for example cell 7 in https://oceanspy.readthedocs.io/en/latest/Kogur.html)

```python
od.plot.horizontal_section('Depth')
```
the plot will NOT display ticks nor labels. Passing `add_labels=True` as an extra argument fixes this issue. See #310 last comment. This is not a bug or anything, as it does not break any test nor does it prevent notebook from finishing when ran. But I think it needs to be addressed. 

I guess it used to be the case that `add_labels=True`? or maybe a change in the behavior plotting by gridliner (cartopy+matplotlib)?

**Comment by ThomasHaine** [comment]
After discussion, we should set `add_labels=True` as the default behaviour.

**Comment by ThomasHaine** [comment]
@Mikejmnez has there been any progress on resolving this issue?

**Comment by Mikejmnez** [comment]
I am very confused. I didn't know I was assigned to this. Either way, no progress. But should be a quick fix!
