### ISSUE TITLE
readthedocs search hangs

### ISSUE THREAD

**Issue by ThomasHaine** [malmans2/oceanspy#356]
Search using the left hand `Search docs` field at https://oceanspy.readthedocs.io/en/latest/index.html. It never returns any search results, just keeps on `Searching...`

**Comment by MaceKuailv** [comment]
It is the same on my side. The doc seems normal, The search bar is automatically generated, so I am not sure which things that we can change is responsible for this error. And I definitely used the search function before. 

A natural explanation is that the readthedocs server is having unusual traffic. I tried several other read the docs sites, and none of them have this error. It does not, however, rule out the possibility. 

How long have you been experiencing this error? @ThomasHaine The hope is that it may go away if we just wait a little longer.

**Comment by ThomasHaine** [comment]
I tried searching 2–3 weeks ago, and the issue was the same.

**Comment by ThomasHaine** [comment]
Hmmm. It works fine now!  Close this issue?

**Comment by Mikejmnez** [comment]
works on my end now (it didn't last week)

**Comment by ThomasHaine** [comment]
Looks like all's well again.
