### ISSUE TITLE
resolve numpy >= 2.0 discrepancies

### ISSUE THREAD

**Issue by Mikejmnez** [malmans2/oceanspy#448]
* OceanSpy version:

### Description

There were some very important new changes with numpy 2.0 releaased earlier this year that have caused some disruption across the numeric/scientific python ecosystem.. It seems that in the case of oceanspy, the failure on the PRs are associated with one of those changes based on the error:

```python
FAILED oceanspy/tests/test_compute_functions.py::test_Ertel_potential_vorticity[True-od_in1] - AttributeError: `np.asfarray` was removed in the NumPy 2.0 release. Use `np.asarray` with a proper dtype instead.
```

### potential solutions
a) pin to numpy < 2.0 (backwards compatibility).
b) migrate to numpy >= 2.0 as a requirement.

I need to take a look, but it may be possible that it is just this same error propagated across (I may be wrong). And so I would recommend b) and so we'll need to update the environments on Sciserver, repo and state clearly that numpy>=2 is required

**Comment by ThomasHaine** [comment]
I think b), migration to the new numpy makes most sense. Please can you explore b), fix, raise a PR, and then I'll liaise with Mitya to get the new version on the SciServer Oceanography container. Thanks!
