### ISSUE TITLE
drop Python 3.9 from github workflows

### ISSUE THREAD

**Issue by Mikejmnez** [malmans2/oceanspy#449]
* OceanSpy version:

### Description

Python 3.9 has already been dropped from xarray testing matrix, and I believe numpy dropped support for 3.9 earlier in April. Python 3.9's end of life is still a year away (see [here](https://devguide.python.org/versions/)), but for testing purposes many packages have already dropped it from their development testing and I suggest OsPy does it as well.

In addition, I would suggest to add Python 3.12 to the testing matrix as it has been out for a year now, is more mature now, and just ahead of the release of 3.13.

**Comment by ThomasHaine** [comment]
I agree. Unless anyone objects, please make the changes and raise a PR.
