### ISSUE TITLE
Wheel security issue

### ISSUE THREAD

**Issue by ThomasHaine** [malmans2/oceanspy#456]
We need to address this wheel security issue: https://github.com/hainegroup/oceanspy/security/dependabot/4

I'm confused why the wheel update can't run automatically, because it doesn't seem to be pinned. Is it because some other required package has pinned it, and we need to wait for it to update?

**Comment by Mikejmnez** [comment]
just took a look at it -- weird indeed. I am re-running the failed build on the #455 PR (python 3.12). It also not clear why it failed (it just said operation cancelled on the `test_open_oceandataset.py`). I will see if re-running this check passes next time, and wheel security issue gets updated after merging that PR.

**Comment by Mikejmnez** [comment]
just to confirm - Re-ran the failing check/build by dependabot's PR (#455). It passed and merging that PR solved the [Wheel security alert](https://github.com/hainegroup/oceanspy/security/dependabot/4). Closing as completed :)
